<a href="https://colab.research.google.com/github/varshithkuravati/ML-practice/blob/main/ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score


In [21]:
# getting the dataset.
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

headnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

dataset = pd.read_csv(path, names = headnames)

dataset.head()


# data preprocessing stage.


x = dataset.iloc[:,:-1]
y = dataset.iloc[:,4]

# instead of going for train and test
# iam going with train, test and validation

x_train, x_temp, y_train, y_temp = train_test_split(x,y, test_size = 0.3)
x_test, x_val, y_test, y_val = train_test_split(x_temp, y_temp, test_size = 0.5)

scaler = StandardScaler()

scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_val = scaler.transform(x_val)

classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
# print(f1_score(y_test, y_pred, average = 'weighted'))




[[10  0  0]
 [ 0  7  0]
 [ 0  0  5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         7
 Iris-virginica       1.00      1.00      1.00         5

       accuracy                           1.00        22
      macro avg       1.00      1.00      1.00        22
   weighted avg       1.00      1.00      1.00        22

1.0


# Week 3

In [22]:
import kagglehub
path = kagglehub.dataset_download("hasibullahaman/traffic-prediction-dataset")

100%|██████████| 83.1k/83.1k [00:00<00:00, 43.3MB/s]

Extracting files...


In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os




# loading the data
data = pd.read_csv(os.path.join(path, "Traffic.csv"))

pd.to_datetime(data["Time"],format="%I:%M:%S %p").dt.hour
pd.to_datetime(data["Time"],format="%I:%M:%S %p").dt.minute

,Time
0,0
1,15
2,30
3,45
4,0
...,...
2971,45
2972,0
2973,15
2974,30
